version: "3.7"

services:
  # exporter:
  assembler:
    build:
      context: "./packages/assembler"
      args:
        - COMPONENTS_LIBRARY=https://github.com/alvimm/troodon-components/tarball/master
  builder:
    build: "./packages/builder"
  proxy:
    build: "./packages/proxy"
    ports:
      - "3000:3000"
    environment:
      - BUILDER_API=http://builder:3000
      - ASSEMBLER_API=http://assembler:3000
  # mapper:
  # renderer: