version: "3.7"

services:
  # exporter:
  builder:
    build: "./packages/builder"
  renderer:
    build: "./packages/renderer"
  proxy:
    build: "./packages/proxy"
    ports:
      - "3000:3000"
    environment:
      - BUILDER_API=http://builder:3000
      - RENDERER_API=http://renderer:3000
  # mapper:
  # renderer: